2022-02-02 11:05:30,988 INFO    MainThread:72 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-02-02 11:05:30,988 INFO    MainThread:72 [wandb_setup.py:_flush():75] Loading settings from /work/wandb/settings
2022-02-02 11:05:30,988 INFO    MainThread:72 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-02 11:05:30,989 INFO    MainThread:72 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-02 11:05:30,989 INFO    MainThread:72 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-02-02 11:05:30,989 INFO    MainThread:72 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-02-02 11:05:30,989 INFO    MainThread:72 [wandb_init.py:_log_setup():386] Logging user logs to /work/wandb/run-20220202_110530-xgb_depth_test/logs/debug.log
2022-02-02 11:05:30,989 INFO    MainThread:72 [wandb_init.py:_log_setup():387] Logging internal logs to /work/wandb/run-20220202_110530-xgb_depth_test/logs/debug-internal.log
2022-02-02 11:05:30,989 INFO    MainThread:72 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f88fefde090>
2022-02-02 11:05:30,989 INFO    MainThread:72 [wandb_init.py:init():420] calling init triggers
2022-02-02 11:05:30,989 INFO    MainThread:72 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {}
2022-02-02 11:05:30,990 INFO    MainThread:72 [wandb_init.py:init():442] re-initializing run, found existing run on stack: xgb_depth_test
2022-02-02 11:05:30,992 INFO    MainThread:72 [wandb_run.py:finish():1468] finishing run cz4041/test-project/xgb_depth_test
2022-02-02 11:05:30,992 INFO    MainThread:72 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-02-02 11:05:30,995 INFO    MainThread:72 [wandb_run.py:_restore():1769] restore
2022-02-02 11:05:31,673 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 571
  total_bytes: 571
}

2022-02-02 11:05:31,787 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 571
  total_bytes: 571
}

2022-02-02 11:05:32,211 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 571
  total_bytes: 323902
}

2022-02-02 11:05:32,313 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 571
  total_bytes: 323902
}

2022-02-02 11:05:32,415 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 323902
  total_bytes: 323902
}

2022-02-02 11:05:32,517 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 323902
  total_bytes: 323902
}

2022-02-02 11:05:32,619 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 323902
  total_bytes: 323902
}

2022-02-02 11:05:32,720 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 323902
  total_bytes: 323902
}

2022-02-02 11:05:32,823 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 323902
  total_bytes: 323902
}

2022-02-02 11:05:33,052 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 323902
  total_bytes: 323902
}

2022-02-02 11:05:33,280 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 323902
  total_bytes: 323902
}
local_info {
}

2022-02-02 11:05:37,010 INFO    MainThread:72 [wandb_run.py:_append_history():2144] rendering history
2022-02-02 11:05:37,011 INFO    MainThread:72 [wandb_run.py:_append_summary():2102] rendering summary
2022-02-02 11:05:37,011 INFO    MainThread:72 [wandb_run.py:_append_files():2194] logging synced files
2022-02-02 11:05:37,021 INFO    MainThread:72 [wandb_init.py:init():471] starting backend
2022-02-02 11:05:37,022 INFO    MainThread:72 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-02 11:05:37,025 INFO    MainThread:72 [backend.py:ensure_launched():219] starting backend process...
2022-02-02 11:05:37,038 INFO    MainThread:72 [backend.py:ensure_launched():225] started backend process with pid: 919
2022-02-02 11:05:37,040 INFO    MainThread:72 [wandb_init.py:init():480] backend started and connected
2022-02-02 11:05:37,048 INFO    MainThread:72 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-02-02 11:05:37,048 INFO    MainThread:72 [wandb_run.py:_label_probe_notebook():931] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-02 11:05:37,048 INFO    MainThread:72 [wandb_init.py:init():550] updated telemetry
2022-02-02 11:05:37,053 INFO    MainThread:72 [wandb_init.py:init():581] communicating current version
2022-02-02 11:05:39,545 INFO    MainThread:72 [wandb_init.py:init():586] got version response 
2022-02-02 11:05:39,545 INFO    MainThread:72 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-02 11:06:09,546 INFO    MainThread:72 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2022-02-02 11:06:09,547 ERROR   MainThread:72 [wandb_init.py:init():601] backend process timed out
2022-02-02 11:06:09,547 ERROR   MainThread:72 [wandb_init.py:init():610] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-02-02 11:06:09,561 ERROR   MainThread:72 [wandb_init.py:init():978] error
Traceback (most recent call last):
  File "/root/venv/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 951, in init
    run = wi.init()
  File "/root/venv/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 614, in init
    backend.cleanup()
  File "/root/venv/lib/python3.7/site-packages/wandb/sdk/backend/backend.py", line 248, in cleanup
    self.interface.join()
  File "/root/venv/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/root/venv/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/root/venv/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/root/venv/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/root/venv/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-02-02 11:10:49,237 INFO    MainThread:72 [wandb_settings.py:_apply_login():1182] Applying login settings: {'api_key': '***REDACTED***'}
2022-02-02 11:10:49,248 INFO    MainThread:72 [wandb_settings.py:_apply_login():1182] Applying login settings: {'api_key': '***REDACTED***'}
2022-02-02 11:10:49,409 INFO    MainThread:72 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-02-02 11:10:49,409 INFO    MainThread:72 [wandb_setup.py:_flush():75] Loading settings from /work/wandb/settings
2022-02-02 11:10:49,409 INFO    MainThread:72 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-02 11:10:49,409 INFO    MainThread:72 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-02 11:10:49,409 INFO    MainThread:72 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-02-02 11:10:49,409 INFO    MainThread:72 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-02-02 11:10:49,409 INFO    MainThread:72 [wandb_init.py:_log_setup():386] Logging user logs to /work/wandb/run-20220202_111049-3tp6u42s/logs/debug.log
2022-02-02 11:10:49,410 INFO    MainThread:72 [wandb_init.py:_log_setup():387] Logging internal logs to /work/wandb/run-20220202_111049-3tp6u42s/logs/debug-internal.log
2022-02-02 11:10:49,410 INFO    MainThread:72 [wandb_init.py:init():420] calling init triggers
2022-02-02 11:10:49,410 INFO    MainThread:72 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {}
2022-02-02 11:10:49,410 INFO    MainThread:72 [wandb_init.py:init():471] starting backend
2022-02-02 11:10:49,410 INFO    MainThread:72 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-02 11:10:49,412 INFO    MainThread:72 [backend.py:ensure_launched():219] starting backend process...
2022-02-02 11:10:49,421 INFO    MainThread:72 [backend.py:ensure_launched():225] started backend process with pid: 1013
2022-02-02 11:10:49,427 INFO    MainThread:72 [wandb_init.py:init():480] backend started and connected
2022-02-02 11:10:49,436 INFO    MainThread:72 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-02-02 11:10:49,436 INFO    MainThread:72 [wandb_run.py:_label_probe_notebook():931] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-02 11:10:49,436 INFO    MainThread:72 [wandb_init.py:init():550] updated telemetry
2022-02-02 11:10:49,443 INFO    MainThread:72 [wandb_init.py:init():581] communicating current version
2022-02-02 11:10:52,121 INFO    MainThread:72 [wandb_init.py:init():586] got version response 
2022-02-02 11:10:52,122 INFO    MainThread:72 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-02 11:10:52,264 INFO    MainThread:72 [wandb_init.py:init():624] starting run threads in backend
2022-02-02 11:10:57,277 INFO    MainThread:72 [wandb_run.py:_console_start():1827] atexit reg
2022-02-02 11:10:57,279 INFO    MainThread:72 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-02-02 11:10:57,279 INFO    MainThread:72 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-02-02 11:10:57,280 INFO    MainThread:72 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-02 11:10:57,281 INFO    MainThread:72 [wandb_init.py:init():651] run started, returning control to user process
2022-02-02 11:10:57,282 INFO    MainThread:72 [wandb_run.py:_config_callback():966] config_cb None None {'boosting_type': 'dart', 'objective': 'multi:softmax', 'num_class': 9, 'max_depth': 2, 'min_child_weight': 20, 'gamma': 1, 'subsample': 0.8, 'colsample_bytree': 0.7, 'tree_method': 'hist', 'eval_metric': 'mlogloss', 'eta': 0.04, 'alpha': 1, 'verbose': 2}
2022-02-02 11:11:09,101 INFO    MainThread:72 [wandb_setup.py:_flush():75] Loading settings from /root/.config/wandb/settings
2022-02-02 11:11:09,102 INFO    MainThread:72 [wandb_setup.py:_flush():75] Loading settings from /work/wandb/settings
2022-02-02 11:11:09,102 INFO    MainThread:72 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-02 11:11:09,102 INFO    MainThread:72 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-02 11:11:09,102 INFO    MainThread:72 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-02-02 11:11:09,102 INFO    MainThread:72 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-02-02 11:11:09,102 INFO    MainThread:72 [wandb_init.py:_log_setup():386] Logging user logs to /work/wandb/run-20220202_111109-wl9xymtv/logs/debug.log
2022-02-02 11:11:09,102 INFO    MainThread:72 [wandb_init.py:_log_setup():387] Logging internal logs to /work/wandb/run-20220202_111109-wl9xymtv/logs/debug-internal.log
2022-02-02 11:11:09,103 INFO    MainThread:72 [wandb_init.py:init():420] calling init triggers
2022-02-02 11:11:09,103 INFO    MainThread:72 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {}
2022-02-02 11:11:09,103 INFO    MainThread:72 [wandb_init.py:init():442] re-initializing run, found existing run on stack: 3tp6u42s
2022-02-02 11:11:09,106 INFO    MainThread:72 [wandb_run.py:finish():1468] finishing run kero0000/my-test-project/3tp6u42s
2022-02-02 11:11:09,106 INFO    MainThread:72 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-02-02 11:11:09,107 INFO    MainThread:72 [wandb_run.py:_restore():1769] restore
2022-02-02 11:11:09,821 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 571
  total_bytes: 571
}

2022-02-02 11:11:09,993 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 571
  total_bytes: 571
}

2022-02-02 11:11:10,352 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 571
  total_bytes: 6976
}

2022-02-02 11:11:10,458 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 571
  total_bytes: 7819
}

2022-02-02 11:11:10,560 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7819
  total_bytes: 7819
}

2022-02-02 11:11:10,662 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7819
  total_bytes: 7819
}

2022-02-02 11:11:10,764 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7819
  total_bytes: 7819
}

2022-02-02 11:11:10,866 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7819
  total_bytes: 7819
}

2022-02-02 11:11:10,968 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7819
  total_bytes: 7819
}

2022-02-02 11:11:11,184 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7819
  total_bytes: 7819
}

2022-02-02 11:11:11,414 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7819
  total_bytes: 7819
}
local_info {
}

2022-02-02 11:11:12,851 INFO    MainThread:72 [wandb_run.py:_append_files():2194] logging synced files
2022-02-02 11:11:12,862 INFO    MainThread:72 [wandb_init.py:init():471] starting backend
2022-02-02 11:11:12,863 INFO    MainThread:72 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-02 11:11:12,867 INFO    MainThread:72 [backend.py:ensure_launched():219] starting backend process...
2022-02-02 11:11:12,875 INFO    MainThread:72 [backend.py:ensure_launched():225] started backend process with pid: 1057
2022-02-02 11:11:12,879 INFO    MainThread:72 [wandb_init.py:init():480] backend started and connected
2022-02-02 11:11:12,889 INFO    MainThread:72 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-02-02 11:11:12,889 INFO    MainThread:72 [wandb_run.py:_label_probe_notebook():931] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-02 11:11:12,889 INFO    MainThread:72 [wandb_init.py:init():550] updated telemetry
2022-02-02 11:11:12,896 INFO    MainThread:72 [wandb_init.py:init():581] communicating current version
2022-02-02 11:11:14,521 INFO    MainThread:72 [wandb_init.py:init():586] got version response 
2022-02-02 11:11:14,521 INFO    MainThread:72 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-02 11:11:14,725 INFO    MainThread:72 [wandb_init.py:init():624] starting run threads in backend
2022-02-02 11:11:17,298 INFO    MainThread:72 [wandb_run.py:_console_start():1827] atexit reg
2022-02-02 11:11:17,300 INFO    MainThread:72 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-02-02 11:11:17,300 INFO    MainThread:72 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-02-02 11:11:17,301 INFO    MainThread:72 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-02 11:11:17,302 INFO    MainThread:72 [wandb_init.py:init():651] run started, returning control to user process
2022-02-02 11:11:17,303 INFO    MainThread:72 [wandb_run.py:_config_callback():966] config_cb None None {'boosting_type': 'dart', 'objective': 'multi:softmax', 'num_class': 9, 'max_depth': 2, 'min_child_weight': 20, 'gamma': 1, 'subsample': 0.8, 'colsample_bytree': 0.7, 'tree_method': 'hist', 'eval_metric': 'mlogloss', 'eta': 0.04, 'alpha': 1, 'verbose': 2}
2022-02-02 11:31:30,627 INFO    MainThread:72 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-02-02 11:31:30,630 INFO    MainThread:72 [wandb_run.py:_restore():1769] restore
2022-02-02 11:31:31,569 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 571
  total_bytes: 571
}

2022-02-02 11:31:31,773 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 571
  total_bytes: 571
}

2022-02-02 11:31:31,998 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 571
  total_bytes: 7702
}

2022-02-02 11:31:32,101 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 571
  total_bytes: 7702
}

2022-02-02 11:31:32,208 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 600
  total_bytes: 7702
}

2022-02-02 11:31:32,314 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5168
  total_bytes: 7702
}

2022-02-02 11:31:32,416 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7702
  total_bytes: 7702
}

2022-02-02 11:31:32,518 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7702
  total_bytes: 7702
}

2022-02-02 11:31:32,620 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7702
  total_bytes: 7702
}

2022-02-02 11:31:32,722 INFO    MainThread:72 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7702
  total_bytes: 7702
}

